import { AppState } from "./store";

export const initialState: Omit<AppState, "router"> = {
    loading: {
        isShown: false,
    },
    modals: {
        stageClearModal: {
            isShown: false,
        },
        rightOrWrongModal: {
            isCorrect: false,
            isShown: false,
        }
    },
    stage1: {
        isCleared: false,
        problemNum: 1,
        isSelectMode: false,
        selectedItem: null,
        storageItems: [],
        inTransparentBoxItem: null,
        mysterySlide: null,
        boxA: null,
        smile:null,
    },
    stage2: {
        isCleared: false,
        problemNum: 1,
        isSelectMode: false,
        selectedItem: null,
        storageItems: [],
        inTransparentBoxItem: null,
        mysterySlide: null,
        boxA: null,
        smile:null,
    },
    stage3: {
        isCleared: false,
        problemNum: 1,
        processNum: 1,
        isSelectMode: false,
        selectedItem: null,
        storageItems: [],
        inTransparentBoxItem: null,
        mysterySlide: null,
        boxA: null,
        smile:null,
        smallRoomItems: null,
    },
    stage4: {
        isCleared: false,
        problemNum: 1,
        processNum: 1,
        isSelectMode: false,
        selectedItem: null,
        storageItems: [],
        inTransparentBoxItem: null,
        mysterySlide: null,
        boxA: null,
        smile:null,
        smallRoomItems: null,
    },
    stage5: {
        isCleared: false,
        problemNum: 1,
        processNum: 1,
        isSelectMode: false,
        selectedItem: null,
        storageItems: [],
        inTransparentBoxItem: null,
        mysterySlide: null,
        boxA: null,
        smile:null,
        smallRoomItems: null,
    },
};
